apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sitesecurity.fullname" . }}-keycloak
  labels:
    {{- include "sitesecurity.labels" . | nindent 4 }}
data:
  realm-export.json: |
    {{- .Files.Get "files/realm-export.json" | nindent 4 }}
