{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sitesecurity.fullname" . }}
  labels:
    {{- include "sitesecurity.labels" . | nindent 4 }}
  {{- if .Values.ingress.className }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "sitesecurity.apiHost" . }}
                port:
                  number: {{ .Values.api.port }}
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: {{ include "sitesecurity.authHost" . }}
                port:
                  number: {{ .Values.auth.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "sitesecurity.frontendHost" . }}
                port:
                  number: {{ .Values.frontend.port }}
{{- end }}
