apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sitesecurity.fullname" . }}
  labels:
    {{- include "sitesecurity.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.db.password | quote }}
  keycloak-admin-password: {{ .Values.auth.adminPassword | quote }}
  api-auth-client-secret: {{ .Values.api.authClientSecret | quote }}
